name: qalculate
version: '1.9.99'
summary: The ultimate desktop calculator
description: |
  Qalculate! is a multi-purpose cross-platform desktop calculator. It is small
  and simple to use but with much power and versatility underneath. Features
  include customizable functions, units, arbitrary precision, plotting, and a
  user-friendly interface 

grade: stable
confinement: strict

slots:
  dbus-qalculate:
    interface: dbus
    name: org.gtk.qalculate
    bus: session

apps:
  qalc:
    command: desktop-launch qalc
    plugs: [network]
  gtk:
    command: desktop-launch gp-launch qalculate-gtk
    plugs: [unity7, network, home]
  gnuplot:
    command: desktop-launch gp-launch gnuplot
    plugs: [unity7, home]

parts:
  libqalculate:
    source: https://github.com/Qalculate/libqalculate.git
    source-tag: master
    plugin: autotools
    build-packages:
      - libncurses5-dev
      - libreadline-dev
      - libcurl4-gnutls-dev
      - libicu-dev
      - libxml2-dev
      - libgmp-dev
      - libmpfr-dev
      - intltool
      - doxygen
    stage-packages:
      - libxml2
    prepare: |
      for p in ../../../patches/lib/*.patch
      do
        cat $p | patch -p1
      done
    install: |
      echo Stripping qalc
      strip $SNAPCRAFT_PART_INSTALL/bin/qalc
    prime:
      - -include
      - -lib/pkgconfig
      - -lib/*.a
      - -share/doc
      - -usr/share/doc
      - -usr/share/lintian

  qalculate-gtk:
    source: https://github.com/Qalculate/qalculate-gtk.git
    source-tag: master
    plugin: autotools
    build-packages:
      - libgmp-dev
      - libgtk-3-dev
      - libxml2-dev
      - intltool
    install: |
      echo Stripping qalculate-gtk
      strip $SNAPCRAFT_PART_INSTALL/bin/qalculate-gtk
    after:
      - libqalculate
      - desktop-gtk3
    prime:
      - -share/applications
      - -share/doc

  gnuplot:
    source: https://sourceforge.net/projects/gnuplot/files/gnuplot/5.0.6/gnuplot-5.0.6.tar.gz
    plugin: autotools
    configflags:
      - --without-lasergnu
      - --with-png
      - --with-gd
      - --without-lisp-files
      - --without-linux-vga
      - --with-readline=bsd
      - --disable-wxwidgets
    build-packages:
      - libcerf-dev
      - libcairo2-dev
      - libedit-dev
      - libgd2-dev
      - liblua5.1-dev
      - lua5.1
      - libpango1.0-dev
      - libpng-dev
      - libx11-dev
      - libxt-dev
      - pkg-config
      - zlib1g-dev
    prime:
      - -share/applications
      - -share/doc
      - -share/man
    after:
      - desktop-gtk3
    install: |
      echo Stripping gnuplot
      strip $SNAPCRAFT_PART_INSTALL/bin/gnuplot
      strip $SNAPCRAFT_PART_INSTALL/libexec/gnuplot/5.0/gnuplot_x11

  gp-launch:
    plugin: dump
    source: launcher
    organize:
      gp-launch: bin/
