.TH QALCULATE\-GTK 1 "7 July 2020"
.SH NAME
qalculate-gtk \- Powerful and easy to use desktop calculator
.SH SYNOPSIS
.B qalculate-gtk
.RI [ options ]
.RI [ expression ]
.SH DESCRIPTION
Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
to use but provides power and versatility normally reserved for complicated
math packages, as well as useful tools for everyday needs (such as currency
conversion and percent calculation). Features include a large library of
customizable functions, unit calculations and conversion, physical constants,
symbolic calculations (including integrals and equations), arbitrary precision,
uncertainty propagation, interval arithmetic, plotting, and a user-friendly
interface.
.PP
\fBqalculate-gtk\fP is the graphical user interface of Qalculate!.
.SH OPTIONS
.PP
.TP 8
.B \-n, \-\-new\-instance
start a new instance of the application
.PP
.TP 8
.B \-\-title \fITITLE\fP
specify the window title
.PP
.TP 8
.B \-v, \-\-version
show application version and exit
.PP
There are additional general options (not specific for the application) which
can be listed with
.B \-\-help
.SH "SEE ALSO"
Full documentation at
.I https://qalculate.github.io/manual/
or in the Help menu
.SH BUGS
Please report any bugs at
.I https://github.com/Qalculate/qalculate-gtk/issues
.SH AUTHORS
qalculate-gtk was written by Hanna Knutsson <hanna.knutsson@protonmail.com>.
